- job_name: node_exporter_ec2
  static_configs:
  - targets:  ['3.139.234.192:9100'] # Public IP Ubuntu: Port 9100
- job_name: blackbox
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - 3.139.234.192/events # Public IP Ubuntu: Port 80
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: prometheus-blackbox-exporter.monitoring:9115